version: "3"
services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: frostornge
      MYSQL_DATABASE: indexer
    volumes:
      - ./tmp/db:/var/lib/mysql